import os
import nbformat as nbf

def create_notebook(filename, cells):
    nb = nbf.v4.new_notebook()
    nb_cells = []
    for cell_type, content in cells:
        if cell_type == "markdown":
            nb_cells.append(nbf.v4.new_markdown_cell(content))
        elif cell_type == "code":
            nb_cells.append(nbf.v4.new_code_cell(content))
    nb['cells'] = nb_cells
    
    os.makedirs('solutions', exist_ok=True)
    filepath = os.path.join('solutions', filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    print(f"Created {filepath}")

# 6. Chatbot with Persistent Memory (LangGraph)
n6_cells = [
    ("markdown", "# 6. Chatbot with Persistent Memory (LangGraph)\n**Industry:** Banking\n\nBuild a chatbot using LangGraph that remembers conversation history across multiple turns and sessions using SQLite checkpointing."),
    ("code", "!pip install langgraph langchain langchain-google-genai python-dotenv"),
    ("code", "import os\nfrom typing import Annotated\nfrom typing_extensions import TypedDict\nfrom langgraph.graph import StateGraph, START, END\nfrom langgraph.graph.message import add_messages\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom langgraph.checkpoint.sqlite import SqliteSaver\nimport sqlite3\n\n# os.environ['GOOGLE_API_KEY'] = 'your-api-key-here'\n\nclass State(TypedDict):\n    messages: Annotated[list, add_messages]\n\nllm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\")\n\ndef chatbot(state: State):\n    return {\"messages\": [llm.invoke(state[\"messages\"])]}\n\ngraph_builder = StateGraph(State)\ngraph_builder.add_node(\"chatbot\", chatbot)\ngraph_builder.add_edge(START, \"chatbot\")\ngraph_builder.add_edge(\"chatbot\", END)\n\nconn = sqlite3.connect(\"checkpoints.sqlite\", check_same_thread=False)\nmemory = SqliteSaver(conn)\n\ngraph = graph_builder.compile(checkpointer=memory)\n\nconfig = {\"configurable\": {\"thread_id\": \"customer_123\"}}\n\n# Session 1\nuser_input = \"Hi, my loan application ID is 987654.\"\nevents = graph.stream({\"messages\": [(\"user\", user_input)]}, config)\nfor event in events:\n    for value in event.values():\n        print(\"Assistant:\", value[\"messages\"][-1].content)\n\nprint(\"\\n--- Restarting Script (Session 2) ---\\n\")\n\n# Session 2\nuser_input = \"Can you tell me what my loan application ID was?\"\nevents = graph.stream({\"messages\": [(\"user\", user_input)]}, config)\nfor event in events:\n    for value in event.values():\n        print(\"Assistant:\", value[\"messages\"][-1].content)")
]

# 7. ReAct Agent from Scratch
n7_cells = [
    ("markdown", "# 7. ReAct Agent from Scratch\n**Industry:** Supply Chain\n\nImplement a ReAct (Reason + Act) agent using LangGraph that answers questions by reasoning step-by-step and calling an external tool."),
    ("code", "!pip install langgraph langchain langchain-google-genai requests"),
    ("code", "import json\nimport requests\nfrom typing import Annotated, TypedDict\nfrom langchain_core.messages import SystemMessage, HumanMessage, ToolMessage, AIMessage\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom langchain_core.tools import tool\nfrom langgraph.graph import StateGraph, START, END\nfrom langgraph.graph.message import add_messages\nfrom langgraph.prebuilt import ToolNode\n\n@tool\ndef tracking_api(shipment_id: str) -> str:\n    \"\"\"Get the current status and location of a shipment by ID.\"\"\"\n    # Mocking a logistics API\n    data = {\n        \"4521\": \"In transit, currently in Chicago, arriving tomorrow.\",\n        \"9999\": \"Delivered on Monday.\"\n    }\n    return data.get(shipment_id, \"Shipment not found.\")\n\ntools = [tracking_api]\nllm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\").bind_tools(tools)\n\nclass AgentState(TypedDict):\n    messages: Annotated[list, add_messages]\n\ndef reason(state: AgentState):\n    response = llm.invoke(state[\"messages\"])\n    return {\"messages\": [response]}\n\ndef should_continue(state: AgentState):\n    last_message = state[\"messages\"][-1]\n    if last_message.tool_calls:\n        return \"tools\"\n    return END\n\nworkflow = StateGraph(AgentState)\nworkflow.add_node(\"reason\", reason)\nworkflow.add_node(\"tools\", ToolNode(tools))\n\nworkflow.add_edge(START, \"reason\")\nworkflow.add_conditional_edges(\"reason\", should_continue, [\"tools\", END])\nworkflow.add_edge(\"tools\", \"reason\")\n\napp = workflow.compile()\n\nquery = \"Where is shipment #4521 right now and will it arrive on time?\"\nfor event in app.stream({\"messages\": [HumanMessage(content=query)]}):\n    for node, value in event.items():\n        msg = value[\"messages\"][-1]\n        if isinstance(msg, AIMessage) and msg.tool_calls:\n            print(f\"\\n[Reasoning -> Action]: Thinking about calling tool {msg.tool_calls[0]['name']}\")\n        elif isinstance(msg, ToolMessage):\n            print(f\"\\n[Observation]: {msg.content}\")\n        elif isinstance(msg, AIMessage):\n            print(f\"\\n[Final Answer]: {msg.content}\")")
]

# 8. Reflexion Agent (Self-Critique Loop)
n8_cells = [
    ("markdown", "# 8. Reflexion Agent (Self-Critique Loop)\n**Industry:** Consulting Services\n\nBuild an agent that answers a client question/brief, critiques its own answer, and revises it — repeating until a quality threshold or max iterations is reached."),
    ("code", "!pip install langgraph langchain langchain-google-genai pydantic"),
    ("code", "from typing import TypedDict\nfrom langchain_core.prompts import ChatPromptTemplate\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom pydantic import BaseModel, Field\nfrom langgraph.graph import StateGraph, START, END\n\nllm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\")\n\nclass Critique(BaseModel):\n    feedback: str = Field(description=\"Constructive criticism of the answer\")\n    is_good_enough: bool = Field(description=\"True if the answer meets professional consulting standards, False otherwise\")\n\ncritique_llm = llm.with_structured_output(Critique)\n\nclass ReflexionState(TypedDict):\n    question: str\n    draft: str\n    feedback: str\n    iterations: int\n\ndef draft_node(state: ReflexionState):\n    if state.get(\"feedback\"):\n        prompt = f\"Revise this draft based on the feedback.\\n\\nDraft: {state['draft']}\\nFeedback: {state['feedback']}\"\n    else:\n        prompt = f\"Draft an initial consulting answer for: {state['question']}\"\n    response = llm.invoke(prompt)\n    return {\"draft\": response.content, \"iterations\": state.get(\"iterations\", 0) + 1}\n\ndef critique_node(state: ReflexionState):\n    prompt = f\"Critique this consulting strategy.\\nQuestion: {state['question']}\\nDraft: {state['draft']}\"\n    eval = critique_llm.invoke(prompt)\n    return {\"feedback\": eval.feedback, \"is_good_enough\": eval.is_good_enough}\n\ndef route(state: ReflexionState):\n    if state.get(\"is_good_enough\") or state[\"iterations\"] >= 3:\n        return END\n    return \"draft_node\"\n\nworkflow = StateGraph(ReflexionState)\nworkflow.add_node(\"draft_node\", draft_node)\nworkflow.add_node(\"critique_node\", critique_node)\n\nworkflow.add_edge(START, \"draft_node\")\nworkflow.add_edge(\"draft_node\", \"critique_node\")\nworkflow.add_conditional_edges(\"critique_node\", route, [\"draft_node\", END])\n\napp = workflow.compile()\n\ninputs = {\"question\": \"Outline a market-entry strategy for a new EV brand in India.\", \"iterations\": 0}\nfor event in app.stream(inputs):\n    for k, v in event.items():\n        if k == \"draft_node\":\n            print(f\"\\n[Draft Iteration {v['iterations']}]:\\n\", v['draft'][:200], \"...\")\n        elif k == \"critique_node\":\n            print(f\"\\n[Critique]:\\n\", v['feedback'])\n            print(\"Pass?\", v['is_good_enough'])")
]

# 9. Supervisor Multi-Agent System
n9_cells = [
    ("markdown", "# 9. Supervisor Multi-Agent System\n**Industry:** Manufacturing\n\nBuild a hierarchical multi-agent system where a 'Supervisor' agent routes requests to specialized agents (Researcher, Coder, Enhancer) and validates the final output."),
    ("code", "!pip install langgraph langchain langchain-google-genai pydantic langchain_experimental"),
    ("code", "from typing import TypedDict, Literal\nfrom langchain_core.prompts import ChatPromptTemplate\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom pydantic import BaseModel\nfrom langgraph.graph import StateGraph, START, END\n\nclass Router(BaseModel):\n    next_node: Literal[\"Researcher\", \"Coder\", \"FINISH\"]\n\nllm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\")\nrouter_llm = llm.with_structured_output(Router)\n\nclass State(TypedDict):\n    query: str\n    research_data: str\n    code_data: str\n    final_answer: str\n\ndef supervisor(state: State):\n    prompt = f\"You are a Supervisor. Next steps?\\nQuery: {state['query']}\\nResearch: {state.get('research_data', 'None')}\\nCode: {state.get('code_data', 'None')}\"\n    decision = router_llm.invoke(prompt)\n    return {\"next_node\": decision.next_node}\n\ndef researcher(state: State):\n    print(\"-> Researcher working...\")\n    return {\"research_data\": \"Found info: Sensor 3 is prone to overheating when voltage > 5V.\"}\n\ndef coder(state: State):\n    print(\"-> Coder working...\")\n    return {\"code_data\": \"def check_voltage(v): return v > 5\"}\n\nworkflow = StateGraph(State)\nworkflow.add_node(\"Supervisor\", supervisor)\nworkflow.add_node(\"Researcher\", researcher)\nworkflow.add_node(\"Coder\", coder)\n\nworkflow.add_edge(START, \"Supervisor\")\nworkflow.add_conditional_edges(\"Supervisor\", lambda state: state.get(\"next_node\"), {\n    \"Researcher\": \"Researcher\",\n    \"Coder\": \"Coder\",\n    \"FINISH\": END\n})\nworkflow.add_edge(\"Researcher\", \"Supervisor\")\nworkflow.add_edge(\"Coder\", \"Supervisor\")\n\napp = workflow.compile()\n\nquery = \"research causes of downtime on Line 3 and write code to analyze the sensor logs\"\nfor event in app.stream({\"query\": query}):\n    pass # Log outputs are inside nodes")
]

# 10. Human-in-the-Loop Approval Workflow
n10_cells = [
    ("markdown", "# 10. Human-in-the-Loop Approval Workflow\n**Industry:** Financial Services\n\nBuild a LangGraph workflow that pauses execution and waits for human approval before proceeding with a sensitive action (e.g., executing a trade)."),
    ("code", "!pip install langgraph langchain langchain-google-genai"),
    ("code", "from typing import TypedDict, Annotated\nfrom langgraph.graph import StateGraph, START, END\nfrom langgraph.checkpoint.memory import MemorySaver\n\nclass TradeState(TypedDict):\n    trade_details: str\n    approved: bool\n\ndef prep_trade(state: TradeState):\n    print(f\"\\n[System] Prepping trade: {state['trade_details']}\")\n    return state\n\ndef execute_trade(state: TradeState):\n    if state.get(\"approved\"):\n        print(\"\\n[System] Trade Executed successfully!\")\n    else:\n        print(\"\\n[System] Trade was REJECTED.\")\n    return state\n\nworkflow = StateGraph(TradeState)\nworkflow.add_node(\"prep_trade\", prep_trade)\nworkflow.add_node(\"execute_trade\", execute_trade)\n\nworkflow.add_edge(START, \"prep_trade\")\nworkflow.add_edge(\"prep_trade\", \"execute_trade\")\nworkflow.add_edge(\"execute_trade\", END)\n\nmemory = MemorySaver()\napp = workflow.compile(checkpointer=memory, interrupt_before=[\"execute_trade\"])\n\nconfig = {\"configurable\": {\"thread_id\": \"trade_1\"}}\nstate = {\"trade_details\": \"Buy 100 shares of AAPL\", \"approved\": False}\n\n# Run until interrupt\nprint(\"Starting workflow...\")\napp.invoke(state, config=config)\n\n# User provides approval\nprint(\"\\n--- WAITING FOR HUMAN APPROVAL ---\")\nuser_input = \"yes\"\n\n# Update state and resume\napp.update_state(config, {\"approved\": user_input.lower() == \"yes\"})\nprint(\"Resuming workflow...\")\napp.invoke(None, config=config)")
]

if __name__ == "__main__":
    create_notebook("06_persistent_chatbot.ipynb", n6_cells)
    create_notebook("07_react_agent.ipynb", n7_cells)
    create_notebook("08_reflexion_agent.ipynb", n8_cells)
    create_notebook("09_supervisor_multiagent.ipynb", n9_cells)
    create_notebook("10_human_in_loop.ipynb", n10_cells)
