import os
import nbformat as nbf

def create_notebook(filename, cells):
    nb = nbf.v4.new_notebook()
    nb_cells = []
    for cell_type, content in cells:
        if cell_type == "markdown":
            nb_cells.append(nbf.v4.new_markdown_cell(content))
        elif cell_type == "code":
            nb_cells.append(nbf.v4.new_code_cell(content))
    nb['cells'] = nb_cells
    
    os.makedirs('solutions', exist_ok=True)
    filepath = os.path.join('solutions', filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    print(f"Created {filepath}")

# 7. ReAct Agent from Scratch (Using Real API)
n7_cells = [
    ("markdown", "# 7. ReAct Agent from Scratch\n**Industry:** Supply Chain\n\nImplement a ReAct (Reason + Act) agent using LangGraph that answers questions by reasoning step-by-step and calling an external tool."),
    ("code", "!pip install langgraph langchain langchain-google-genai requests"),
    ("code", "import json\nimport requests\nfrom typing import Annotated, TypedDict\nfrom langchain_core.messages import SystemMessage, HumanMessage, ToolMessage, AIMessage\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom langchain_core.tools import tool\nfrom langgraph.graph import StateGraph, START, END\nfrom langgraph.graph.message import add_messages\nfrom langgraph.prebuilt import ToolNode\nimport os\n\n@tool\ndef tracking_api(shipment_id: str) -> str:\n    \"\"\"Get the current status and location of a shipment by ID using a real public API.\"\"\"\n    # Using a public ZipCode API as a mock for \"Logistics location\"\n    # e.g., if shipment_id is a zip code like 90210, it tells us where the package is.\n    if len(shipment_id) != 5 or not shipment_id.isdigit():\n        return \"Error: Please provide a 5-digit zip code as the shipment ID to track its location.\"\n    \n    response = requests.get(f\"https://api.zippopotam.us/us/{shipment_id}\")\n    if response.status_code == 200:\n        data = response.json()\n        place = data['places'][0]\n        return f\"Shipment {shipment_id} is currently at a facility in {place['place name']}, {place['state']}. Status: In Transit.\"\n    else:\n        return \"Shipment not found or tracking API is down.\"\n\ntools = [tracking_api]\nllm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\").bind_tools(tools)\n\nclass AgentState(TypedDict):\n    messages: Annotated[list, add_messages]\n\ndef reason(state: AgentState):\n    response = llm.invoke(state[\"messages\"])\n    return {\"messages\": [response]}\n\ndef should_continue(state: AgentState):\n    last_message = state[\"messages\"][-1]\n    if last_message.tool_calls:\n        return \"tools\"\n    return END\n\nworkflow = StateGraph(AgentState)\nworkflow.add_node(\"reason\", reason)\nworkflow.add_node(\"tools\", ToolNode(tools))\n\nworkflow.add_edge(START, \"reason\")\nworkflow.add_conditional_edges(\"reason\", should_continue, [\"tools\", END])\nworkflow.add_edge(\"tools\", \"reason\")\n\napp = workflow.compile()\n\nquery = \"Where is shipment #90210 right now and what state is it in?\"\nfor event in app.stream({\"messages\": [HumanMessage(content=query)]}):\n    for node, value in event.items():\n        msg = value[\"messages\"][-1]\n        if isinstance(msg, AIMessage) and msg.tool_calls:\n            print(f\"\\n[Reasoning -> Action]: Thinking about calling tool {msg.tool_calls[0]['name']} with args {msg.tool_calls[0]['args']}\")\n        elif isinstance(msg, ToolMessage):\n            print(f\"\\n[Observation]: {msg.content}\")\n        elif isinstance(msg, AIMessage):\n            print(f\"\\n[Final Answer]: {msg.content}\")")
]

# 11. Comparing Text Chunking Strategies
n11_cells = [
    ("markdown", "# 11. Comparing Text Chunking Strategies for RAG\n**Industry:** Medical Equipments\n\nImplement and compare 4 different text chunking strategies on the same manual and evaluate them."),
    ("code", "!pip install langchain langchain-experimental chromadb sentence-transformers langchain-community pandas tabulate"),
    ("code", "from langchain_community.document_loaders import TextLoader\nfrom langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter\nfrom langchain_experimental.text_splitter import SemanticChunker\nfrom langchain_community.embeddings import HuggingFaceEmbeddings\nfrom langchain_community.vectorstores import Chroma\nimport pandas as pd\nimport os\n\nwith open('manual.txt', 'w') as f:\n    f.write(\"The MRI scanner uses magnetic fields. It must be cooled with liquid helium at all times to maintain superconductivity.\\n\\nMaintenance requires checking helium levels daily using the dipstick tool. Do not bring metal objects near the machine as they will become projectiles.\\n\\nEmergency shutoff is located on the wall to the left of the console. Press the red button in case of fire or a quenching event.\\n\\nA quench happens when the liquid helium boils off rapidly, releasing gas into the room. Evacuate immediately if this occurs.\")\n\nloader = TextLoader('manual.txt')\ndocs = loader.load()\n\nembedder = HuggingFaceEmbeddings(model_name=\"all-MiniLM-L6-v2\")\n\n# 1. Fixed-size chunking\nfixed = CharacterTextSplitter(chunk_size=100, chunk_overlap=0, separator=\" \").split_documents(docs)\n# 2. Recursive chunking\nrecursive = RecursiveCharacterTextSplitter(chunk_size=100, chunk_overlap=20).split_documents(docs)\n# 3. Semantic chunking\nsemantic = SemanticChunker(embedder).split_documents(docs)\n# 4. Sliding Window (implemented via Recursive with large overlap)\nsliding = RecursiveCharacterTextSplitter(chunk_size=100, chunk_overlap=80).split_documents(docs)\n\ncollections = {\n    \"Fixed\": Chroma.from_documents(fixed, embedder, collection_name=\"fixed\"),\n    \"Recursive\": Chroma.from_documents(recursive, embedder, collection_name=\"recursive\"),\n    \"Semantic\": Chroma.from_documents(semantic, embedder, collection_name=\"semantic\"),\n    \"Sliding\": Chroma.from_documents(sliding, embedder, collection_name=\"sliding\"),\n}\n\nquestions = [\"Where is the emergency shutoff?\", \"What happens during a quench?\"]\n\nresults = []\nfor q in questions:\n    for strategy_name, db in collections.items():\n        retrieved = db.similarity_search(q, k=1)[0].page_content\n        results.append({\"Question\": q, \"Strategy\": strategy_name, \"Top Chunk\": retrieved})\n\ndf = pd.DataFrame(results)\nprint(df.to_markdown(index=False))")
]

# 14. Memory-Aware Chatbot with Mem0
n14_cells = [
    ("markdown", "# 14. Memory-Aware Chatbot with Mem0 + Vector DB\n**Industry:** Tourism\n\nBuild a chatbot with hybrid memory using Mem0 and dynamically retrieve preferences."),
    ("code", "!pip install mem0ai langchain-google-genai"),
    ("code", "import os\nfrom mem0 import Memory\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom langchain_core.messages import HumanMessage, SystemMessage\n\n# Mem0 setup (uses default local SQLite/Chroma if no cloud API keys are provided)\nos.environ[\"OPENAI_API_KEY\"] = \"mock\" # Mock key to prevent mem0 from complaining if using local embeddings\nmemory = Memory()\n\n# We will use Gemini for the conversational generation\nllm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\")\n\nuser_id = \"traveler_99\"\n\ndef chat(message: str):\n    # 1. Retrieve relevant memories\n    previous_memories = memory.search(message, user_id=user_id)\n    context = \"\\n\".join([m[\"memory\"] for m in previous_memories]) if previous_memories else \"None\"\n    \n    # 2. Generate response with context\n    prompt = f\"You are a travel concierge. \\nUser Preferences/History: {context}\\n\\nUser: {message}\"\n    response = llm.invoke([HumanMessage(content=prompt)])\n    \n    # 3. Store the new message in memory for future extraction\n    memory.add(message, user_id=user_id)\n    \n    return response.content\n\nprint(\"--- Session 1 ---\")\nprint(\"User: I am planning a trip to Japan. I love window seats and am strictly vegetarian.\")\nprint(\"Bot:\", chat(\"I am planning a trip to Japan. I love window seats and am strictly vegetarian.\"))\n\nprint(\"\\n--- Session 2 (Later) ---\")\nprint(\"User: Book me a flight to Tokyo and suggest a restaurant.\")\nprint(\"Bot:\", chat(\"Book me a flight to Tokyo and suggest a restaurant.\"))")
]

# 17. Persistent Chat History with Firebase
n17_cells = [
    ("markdown", "# 17. Persistent Chat History with Firebase\n**Industry:** QSR (Quick Service Restaurants)\n\nBuild a chatbot that stores and retrieves conversation history from Firebase Firestore."),
    ("code", "!pip install langchain langchain-google-genai langchain-google-firestore google-cloud-firestore"),
    ("code", "\"\"\"\nTo run this code, you MUST provide a valid Google Cloud Service Account JSON key.\nSet it in your environment: os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'path/to/key.json'\n\"\"\"\nimport os\nfrom langchain_google_firestore import FirestoreChatMessageHistory\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder\nfrom langchain_core.runnables.history import RunnableWithMessageHistory\n\n# Uncomment and point to your project ID\n# PROJECT_ID = \"your-gcp-project-id\"\n# SESSION_ID = \"customer_order_555\"\n# COLLECTION = \"chat_history\"\n\n# Initialize Firestore History\n# chat_history = FirestoreChatMessageHistory(\n#     session_id=SESSION_ID,\n#     collection=COLLECTION,\n#     project_id=PROJECT_ID\n# )\n\n# prompt = ChatPromptTemplate.from_messages([\n#     (\"system\", \"You are a friendly drive-thru assistant for a burger chain.\"),\n#     MessagesPlaceholder(variable_name=\"history\"),\n#     (\"human\", \"{input}\")\n# ])\n\n# llm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\")\n# chain = prompt | llm\n\n# chain_with_history = RunnableWithMessageHistory(\n#     chain,\n#     lambda session_id: FirestoreChatMessageHistory(\n#         session_id=session_id,\n#         collection=COLLECTION,\n#         project_id=PROJECT_ID\n#     ),\n#     input_messages_key=\"input\",\n#     history_messages_key=\"history\",\n# )\n\n# response = chain_with_history.invoke(\n#     {\"input\": \"I want a cheeseburger with no pickles.\"}, \n#     config={\"configurable\": {\"session_id\": SESSION_ID}}\n# )\n# print(response.content)\n\nprint(\"This notebook contains the full Firestore integration code. Provide a GCP Project ID and service account to run it.\")")
]

# 19. Web Scraping Agent with Serper API
n19_cells = [
    ("markdown", "# 19. Web Scraping Agent with Search API Integration\n**Industry:** Retail & E-Commerce\n\nBuild an agent that searches the web using the Serper API, scrapes the top results with BeautifulSoup, and summarizes findings."),
    ("code", "!pip install langchain langchain-google-genai requests beautifulsoup4"),
    ("code", "import requests\nfrom bs4 import BeautifulSoup\nfrom langchain_google_genai import ChatGoogleGenerativeAI\nfrom langchain_core.prompts import ChatPromptTemplate\nimport os\n\n# You need a Serper API key from https://serper.dev/\nSERPER_API_KEY = os.environ.get(\"SERPER_API_KEY\", \"YOUR_SERPER_API_KEY_HERE\")\n\ndef search_google(query: str):\n    if SERPER_API_KEY == \"YOUR_SERPER_API_KEY_HERE\":\n        return [\"https://example.com/mock-pricing\"]\n    \n    url = \"https://google.serper.dev/search\"\n    payload = {\"q\": query, \"num\": 3}\n    headers = {\n        'X-API-KEY': SERPER_API_KEY,\n        'Content-Type': 'application/json'\n    }\n    response = requests.post(url, headers=headers, json=payload)\n    data = response.json()\n    return [item.get('link') for item in data.get('organic', [])]\n\ndef scrape_url(url: str):\n    if \"mock-pricing\" in url:\n        return \"Competitor A is selling running shoes at $50 (20% discount).\"\n    \n    try:\n        response = requests.get(url, timeout=5)\n        soup = BeautifulSoup(response.text, 'html.parser')\n        # Extract paragraphs\n        paragraphs = soup.find_all('p')\n        text = \" \".join([p.get_text() for p in paragraphs])\n        return text[:1000] # Limit to 1000 chars per page\n    except:\n        return \"\"\n\ndef research_query(query: str):\n    urls = search_google(query)\n    combined_content = \"\"\n    for u in urls:\n        print(f\"Scraping {u}...\")\n        combined_content += scrape_url(u) + \"\\n\\n\"\n    \n    llm = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\")\n    prompt = ChatPromptTemplate.from_template(\"Summarize this pricing data from competitors:\\n\\n{data}\")\n    chain = prompt | llm\n    \n    summary = chain.invoke({\"data\": combined_content})\n    return summary.content\n\nprint(research_query(\"latest discount trends for nike running shoes\"))")
]

if __name__ == "__main__":
    create_notebook("07_react_agent.ipynb", n7_cells)
    create_notebook("11_chunking_strategies.ipynb", n11_cells)
    create_notebook("14_mem0_chatbot.ipynb", n14_cells)
    create_notebook("17_persistent_chat_firebase.ipynb", n17_cells)
    create_notebook("19_web_scraping_agent.ipynb", n19_cells)
