/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DomainsSlugRouteImport } from './routes/domains.$slug'
import { Route as ProblemsIdRouteImport } from './routes/problems.$id'
import { Route as SubmissionsIdIndexRouteImport } from './routes/submissions.$id.index'
import { Route as SubmissionsIdGradeRouteImport } from './routes/submissions.$id.grade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsSlugRoute = DomainsSlugRouteImport.update({
  id: '/domains/$slug',
  path: '/domains/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/problems/$id',
  path: '/problems/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIdIndexRoute = SubmissionsIdIndexRouteImport.update({
  id: '/submissions/$id/',
  path: '/submissions/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIdGradeRoute = SubmissionsIdGradeRouteImport.update({
  id: '/submissions/$id/grade',
  path: '/submissions/$id/grade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/submissions/$id/grade': typeof SubmissionsIdGradeRoute
  '/submissions/$id/': typeof SubmissionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/submissions/$id/grade': typeof SubmissionsIdGradeRoute
  '/submissions/$id': typeof SubmissionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/submissions/$id/grade': typeof SubmissionsIdGradeRoute
  '/submissions/$id/': typeof SubmissionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/domains/$slug'
    | '/problems/$id'
    | '/submissions/$id/grade'
    | '/submissions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/domains/$slug'
    | '/problems/$id'
    | '/submissions/$id/grade'
    | '/submissions/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/domains/$slug'
    | '/problems/$id'
    | '/submissions/$id/grade'
    | '/submissions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DomainsSlugRoute: typeof DomainsSlugRoute
  ProblemsIdRoute: typeof ProblemsIdRoute
  SubmissionsIdGradeRoute: typeof SubmissionsIdGradeRoute
  SubmissionsIdIndexRoute: typeof SubmissionsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$slug': {
      id: '/domains/$slug'
      path: '/domains/$slug'
      fullPath: '/domains/$slug'
      preLoaderRoute: typeof DomainsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$id/': {
      id: '/submissions/$id/'
      path: '/submissions/$id'
      fullPath: '/submissions/$id/'
      preLoaderRoute: typeof SubmissionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$id/grade': {
      id: '/submissions/$id/grade'
      path: '/submissions/$id/grade'
      fullPath: '/submissions/$id/grade'
      preLoaderRoute: typeof SubmissionsIdGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DomainsSlugRoute: DomainsSlugRoute,
  ProblemsIdRoute: ProblemsIdRoute,
  SubmissionsIdGradeRoute: SubmissionsIdGradeRoute,
  SubmissionsIdIndexRoute: SubmissionsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
